plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'app.pairs'
version = '1.0.0'

repositories {
    mavenCentral()
}

javafx {
    version = "21.0.2"
    modules = [ 'javafx.controls', 'javafx.graphics' ]
}

application {
    mainClass = 'app.pairs.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

